// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_deleteAllTransformsByEmail from "./routes/api/deleteAllTransformsByEmail.tsx";
import * as $api_deleteTransform from "./routes/api/deleteTransform.tsx";
import * as $api_process from "./routes/api/process.tsx";
import * as $api_retrieveAllTransformsByEmail from "./routes/api/retrieveAllTransformsByEmail.tsx";
import * as $api_retrieveTransform from "./routes/api/retrieveTransform.tsx";
import * as $api_run from "./routes/api/run.tsx";
import * as $api_saveTransform from "./routes/api/saveTransform.tsx";
import * as $design_build from "./routes/design/build.tsx";
import * as $index from "./routes/index.tsx";
import * as $Playground_Playground from "./islands/Playground/Playground.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/deleteAllTransformsByEmail.tsx":
      $api_deleteAllTransformsByEmail,
    "./routes/api/deleteTransform.tsx": $api_deleteTransform,
    "./routes/api/process.tsx": $api_process,
    "./routes/api/retrieveAllTransformsByEmail.tsx":
      $api_retrieveAllTransformsByEmail,
    "./routes/api/retrieveTransform.tsx": $api_retrieveTransform,
    "./routes/api/run.tsx": $api_run,
    "./routes/api/saveTransform.tsx": $api_saveTransform,
    "./routes/design/build.tsx": $design_build,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Playground/Playground.tsx": $Playground_Playground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
